version: "3.8"

services:
  mc:
    build: .
    image: minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - data:/minecraft
    stdin_open: true
    tty: true
    # restart: unless-stopped
volumes:
  data: